### ISSUE TITLE
I have some question about teraranger one

### ISSUE THREAD

**Issue by SunLengyi** [Terabee/teraranger#29]
when I ran the Teraranger one use the command $ rosrun teraranger one _portname:=/dev/ttyUSB0,I got the following error:
```
aaa@aaa-HP-ProDesk-600-G4-SFF:~$ ls -lah /dev/ttyUSB0
crw-rw---- 1 root dialout 188, 0 7月  24 15:25 /dev/ttyUSB0
aaa@ujn-HP-ProDesk-600-G4-SFF:~$ sudo chmod 666 /dev/ttyUSB0
[sudo] aaa 的密码： 
aaa@aaa-HP-ProDesk-600-G4-SFF:~$ rosrun teraranger one _portname:=/dev/ttyUSB0
[ INFO] [1563953346.245499995]: [/teraranger_one] is up and running with the following parameters:
[ INFO] [1563953346.245526939]: [/teraranger_one] portname: /dev/ttyUSB0
[ERROR] [1563953347.260760798]: Timeout or error while reading serial
```
Please have a friend who has encountered this problem to help solve it! Thank you

**Comment by pl-kabaradjian** [comment]
Hello,
This error means that the driver didn't receive data for more than a few seconds. However, if this error is not repeating you might still be receiving ranges correctly.
Can you check the range topic (with `rostopic echo`)  and see if you still receive data?

**Comment by SunLengyi** [comment]
When I run the command rostopic echo /teraranger_one，I can receive the data

**Comment by pl-kabaradjian** [comment]
Hi @SunLengyi,

If you can receive data and this error is not repeating it means the sensor is working properly. You should be able to use the sensor without encountering any issue. This might be caused by some hardware or OS delay at starts but shouldn't interfere with normal operation.

However, if you experience other issues I invite you to contact our support team [here](https://www.terabee.com/contact/).

Have a nice day!
